name: 🐛 Bug Report
description: Report a bug to help us improve the project.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - username

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below as completely as possible.

  - type: input
    id: affected-version
    attributes:
      label: Affected Version
      description: Which version of the software did you encounter the issue in?
      placeholder: e.g., 1.0.0 or main branch
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps To Reproduce
      description: Describe the exact steps you took to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Severity / Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: true